version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SECURE: ${EMAIL_SECURE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      APP_URL: ${APP_URL}
    # restart: unless-stopped
    # networks:
    #   - wiwish-net
    volumes:
      - wiwish-uploads:/app/public/uploads

# Asegúrate de crear un archivo .env.production con el siguiente contenido:
# DATABASE_URL=postgresql://username:password@host:port/database
# JWT_SECRET=tu_secreto_jwt_de_produccion
# Y cualquier otra variable de entorno necesaria

# networks:
#   wiwish-net:
#     driver: bridge 

volumes:
  wiwish-uploads:
    driver: local