version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapea el puerto 5000 del host al puerto 5000 del contenedor
      # Puedes cambiar el puerto del host si es necesario (ej. "80:5000")
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 3008 # La aplicación dentro del contenedor debe escuchar en este puerto
      # DATABASE_URL: "tu_url_de_base_de_datos_de_produccion"
      # JWT_SECRET: "tu_secreto_jwt_de_produccion"
      # Agrega aquí otras variables de entorno necesarias para producción
    # Para cargar variables de entorno desde un archivo (recomendado para secretos):
    # env_file:
    #   - .env.production
    restart: unless-stopped
    # networks:
    #   - wiwish-net
    # volumes:
      # Solo si necesitas persistir datos fuera del contenedor (ej. uploads)
      # - ./uploads:/app/uploads

# networks:
#   wiwish-net:
#     driver: bridge 