version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapea el puerto 5000 del host al puerto 5000 del contenedor
      # Puedes cambiar el puerto del host si es necesario (ej. "80:5000")
      - "5000:5000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT}
    restart: unless-stopped
    # networks:
    #   - wiwish-net
    # volumes:
      # Solo si necesitas persistir datos fuera del contenedor (ej. uploads)
      # - ./uploads:/app/uploads

# Asegúrate de crear un archivo .env.production con el siguiente contenido:
# DATABASE_URL=postgresql://username:password@host:port/database
# JWT_SECRET=tu_secreto_jwt_de_produccion
# Y cualquier otra variable de entorno necesaria

# networks:
#   wiwish-net:
#     driver: bridge 